#!/bin/bash

# This script outputs all of the environment vars
# sef by travis.

echo "---------------------------------"
echo "Default ENV Vars"
echo "---------------------------------"
echo "CI: $CI"
echo "TRAVIS: $TRAVIS"
echo "CONTINUS_INTEGRATION: $CONTINUOUS_INTEGRATION"
echo "DEBIAN_FRONTEND: $DEBIAN_FRONTEND"
echo "HAS_JOSH_K_SEAL_OF_APPROVAL: $HAS_JOSH_K_SEAL_OF_APPROVAL"
echo "USER: $USER"
echo "HOME: $HOME"
echo "LANG: $LANG"
echo "LC_ALL: $LC_ALL"
echo "RAILS_ENV: $RAILS_ENV"
echo "RACK_ENV: $RACK_ENV"
echo "MERB_ENV: $MERB_ENV"
echo "JRUBY_OPTS: $JRUBY_OPTS"
echo "JAVA_HOME: $JAVA_HOME"
echo "---------------------------------"
echo ""


echo "---------------------------------"
echo "TRAVIS ENV Vars"
echo "---------------------------------"
echo "TRAVIS_ALLOW_FAILURES: $TRAVIS_ALLOW_FAILURES"
echo "TRAVIS_BRANCH: $TRAVIS_BRANCH"
echo "TRAVIS_BUILD_ID: $TRAVIS_BUILD_ID"
echo "TRAVIS_BUILD_NUMBER: $TRAVIS_BUILD_NUMBER"
echo "TRAVIS_COMMIT: $TRAVIS_COMMIT"
echo "TRAVIS_COMMIT_MESSAGE: $TRAVIS_COMMIT_MESSAGE"
echo "TRAVIS_COMMIT_RANGE: $TRAVIS_COMMIT_RANGE"
echo "TRAVIS_EVENT_TYPE: $TRAVIS_EVENT_TYPE"
echo "TRAVIS_JOB_ID: $TRAVIS_JOB_ID"
echo "TRAVIS_JOB_NUMBER: $TRAVIS_JOB_NUMBER"
echo "TRAVIS_OS_NAME: $TRAVIS_OS_NAME"
echo "TRAVIS_OSX_IMAGE: $TRAVIS_OSX_IMAGE"
echo "TRAVIS_PULL_REQUEST: $TRAVIS_PULL_REQUEST"
echo "TRAVIS_PULL_REQUEST_BRANCH: $TRAVIS_PULL_REQUEST_BRANCH"
echo "TRAVIS_PULL_REQUEST_SHA: $TRAVIS_PULL_REQUEST_SHA"
echo "TRAVIS_PULL_REQUEST_SLUG: $TRAVIS_PULL_REQUEST_SLUG"
echo "TRAVIS_REPO_SLUG: $TRAVIS_REPO_SLUG"
echo "TRAVIS_SECURE_ENV_VARS: $TRAVIS_SECURE_ENV_VARS"
echo "TRAVIS_SUDO: $TRAVIS_SUDO"
echo "TRAVIS_TEST_RESULT: $TRAVIS_TEST_RESULT"
echo "TRAVIS_TAG: $TRAVIS_TAG"
echo "TRAVIS_BUILD_STAGE_NAME: $TRAVIS_BUILD_STAGE_NAME"
echo "TRAVIS_TAG: $TRAVIS_TAG"
echo "---------------------------------"
echo ""


echo "---------------------------------"
echo "TRAVIS Language Vars"
echo "Set based on language used in project."
echo "---------------------------------"
echo "$TRAVIS_DART_VERSION"
echo "TRAVIS_GO_VERSION: $TRAVIS_GO_VERSION"
echo "TRAVIS_HAXE_VERSION: $TRAVIS_HAXE_VERSION"
echo "TRAVIS_JDK_VERSION: $TRAVIS_JDK_VERSION"
echo "TRAVIS_JULIA_VERSION: $TRAVIS_JULIA_VERSION"
echo "TRAVIS_NODE_VERSION: $TRAVIS_NODE_VERSION"
echo "TRAVIS_OTP_RELEASE: $TRAVIS_OTP_RELEASE"
echo "TRAVIS_PERL_VERSION: $TRAVIS_PERL_VERSION"
echo "TRAVIS_PHP_VERSION: $TRAVIS_PHP_VERSION"
echo "TRAVIS_PYTHON_VERSION: $TRAVIS_PYTHON_VERSION"
echo "TRAVIS_R_VERSION: $TRAVIS_R_VERSION"
echo "TRAVIS_RUBY_VERSION: $TRAVIS_RUBY_VERSION"
echo "TRAVIS_RUST_VERSION: $TRAVIS_RUST_VERSION"
echo "TRAVIS_SCALA_VERSION: $TRAVIS_SCALA_VERSION"
echo "---------------------------------"
echo ""


echo "---------------------------------"
echo "TRAVIS Software Specific Vars"
echo "---------------------------------"
echo "TRAVIS_MARIADB_VERSION: $TRAVIS_MARIADB_VERSION"
echo "---------------------------------"
echo ""

echo "---------------------------------"
echo "TRAVIS XCODE Vars"
echo "---------------------------------"
echo "TRAVIS_XCODE_SDK: $TRAVIS_XCODE_SDK"
echo "TRAVIS_XCODE_SCHEME: $TRAVIS_XCODE_SCHEME"
echo "TRAVIS_XCODE_PROJECT: $TRAVIS_XCODE_PROJECT"
echo "TRAVIS_XCODE_WORKSPACE: $TRAVIS_XCODE_WORKSPACE"
echo "---------------------------------"
echo ""

